### ISSUE TITLE
Python session

### ISSUE THREAD

**Issue by brunj7** [NCEAS/oss-lessons#18]
The participants have asked to have an introduction to Python.

Duration: 1h30

Pre-session reading to be exposed to the syntax: <https://github.com/NCEAS/training-jupyter-notebook/blob/master/python4Rusers.md>

### Purpose: Expose participants to the use of `Python` for scientific analysis

- Why Python and how to install it + warning for ArcGIS users on how to not break your install
- Quick overview of the SciPy stack: SciPy, NumPy, Pandas, Scikits (image and learn), matplotlib
- IPython
- Walk through Data Wrangling with `pandas`: Similar to what we have seen using the tidyverse. Can reuse this wrangling on Zillow data: <https://github.com/NCEAS/training-jupyter-notebook/blob/master/SB-housing-wrangling.ipynb: + adding a join example with census data
- Hands on:
  - quick basic syntax overview
  - exercise on SEAMAP:
  - One plot with `seaborn` (or ggpy?)
- Facultatif: Jupyter notebook

### Learning outcomes

- Know the scope of the core Python modules for scientific analysis
- Know how to start IPython
- Know how to do basic data manipulations with `pandas`
- Know how to do a plot with `seaborn`

**Comment by mbjones** [comment]
Julien, this looks great, thanks.  It may be a bit too much material for 90 minutes, but lets evaluate as you get the details worked out.  Also, it might be nice to use a more ecologically relevant data set.  The SEAMAP data set the class is using is pretty well structured, so that might be an option, unless you think that will make it to complex.

**Comment by brunj7** [comment]
Ended up showing the Zillow example for the time available
